version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./dorado-exchange-api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./dorado-exchange-frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PUBLIC_API_URL: ${PUBLIC_API_URL}

volumes:
  postgres_data:
    driver: local