export type RouteConfig = {
  path: string
  roles: string[]
  desktopLabel: string
  mobileLabel: string
  desktopDisplay: boolean
  mobileDisplay: boolean
  footerDisplay: boolean
}

export const protectedRoutes: Record<string, RouteConfig> = {
  buy: {
    path: '/buy',
    roles: [],
    desktopLabel: 'Buy',
    mobileLabel: 'Buy from Us',
    desktopDisplay: true,
    mobileDisplay: true,
    footerDisplay: false,
  },
  sell: {
    path: '/sell',
    roles: [],
    desktopLabel: 'Sell',
    mobileLabel: 'Sell to Us',
    desktopDisplay: true,
    mobileDisplay: true,
    footerDisplay: false,
  },
  orders: {
    path: '/orders',
    roles: ['user', 'admin'],
    desktopLabel: 'Orders',
    mobileLabel: 'Orders',
    desktopDisplay: true,
    mobileDisplay: false,
    footerDisplay: false,
  },
  resources: {
    path: '/resources',
    roles: [],
    desktopLabel: 'Resources',
    mobileLabel: 'Resources',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  admin: {
    path: '/admin',
    roles: ['admin'],
    desktopLabel: 'Admin',
    mobileLabel: 'Admin',
    desktopDisplay: true,
    mobileDisplay: true,
    footerDisplay: false,
  },
  account: {
    path: '/account',
    roles: ['user', 'admin'],
    desktopLabel: 'Account',
    mobileLabel: 'Account',
    desktopDisplay: true,
    mobileDisplay: false,
    footerDisplay: false,
  },
  authentication: {
    path: '/authentication',
    roles: [],
    desktopLabel: 'Authentication',
    mobileLabel: 'Authentication',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  salesTax: {
    path: '/sales-tax',
    roles: [],
    desktopLabel: 'Sales Tax',
    mobileLabel: 'Sales Tax',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  termsAndCondtions: {
    path: '/terms-and-conditions',
    roles: [''],
    desktopLabel: 'Terms and Conditions',
    mobileLabel: 'Terms and Conditions',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  privacyPolicy: {
    path: '/privacy-policy',
    roles: [''],
    desktopLabel: 'Privacy Policy',
    mobileLabel: 'Privacy Policy',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  changeEmail: {
    path: '/change-email',
    roles: ['user', 'admin'],
    desktopLabel: 'Change Email',
    mobileLabel: 'Change Email',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  changePassword: {
    path: '/change-password',
    roles: ['admin', 'user'],
    desktopLabel: 'Change Password',
    mobileLabel: 'Change Password',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  checkout: {
    path: '/checkout',
    roles: ['user', 'admin'],
    desktopLabel: 'Checkout',
    mobileLabel: 'Checkout',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  orderPlaced: {
    path: '/order-placed',
    roles: ['user', 'admin'],
    desktopLabel: 'Order Placed',
    mobileLabel: 'Order Placed',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  resetPassword: {
    path: '/reset-password',
    roles: ['user', 'admin'],
    desktopLabel: 'Reset Password',
    mobileLabel: 'Reset Password',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  salesOrderCheckout: {
    path: '/sales-order-checkout',
    roles: ['user', 'admin'],
    desktopLabel: 'Sales Order Checkout',
    mobileLabel: 'Sales Order Checkout',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  verifyEmail: {
    path: '/verify-email',
    roles: ['user', 'admin'],
    desktopLabel: 'Verify Email',
    mobileLabel: 'Verify Email',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
  verifyLogin: {
    path: '/verify-login',
    roles: ['user', 'admin'],
    desktopLabel: 'Verify Login',
    mobileLabel: 'Verify Login',
    desktopDisplay: false,
    mobileDisplay: false,
    footerDisplay: false,
  },
}
